from .navbar import navbar
from .footer import footer
from .simple_graph import simple_graph
from .map_graph import map_graph
from .line_graph import line_graph
from .table_graph import table_graph
from .horizontal_bar_graph import horizontal_bar_graph
from .bpm_by_contry_graph import bpm_by_contry_graph
from .loudness_energy_graph import loudness_energy_graph