from .navbar import navbar
from .footer import footer
from .popularity_by_countries_graph import popularity_by_countries_graph
from .map_graph import create_map_graph
from .duration_by_genre_graph import duration_by_genre_graph
from .bpm_by_contry_graph import bpm_by_contry_graph
from .loudness_energy_graph import loudness_energy_graph
from .genre_comparing_graph import create_dual_comparaison